### ISSUE TITLE
pyswath installation: ModuleError not defined

### ISSUE THREAD

**Issue by benbovy** [robertxa/pyswath#1]
When installing pyswath without having installed the dependencies first, we get an error but the wrong one:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fg/08wyb9fs38b0f6d68qpxkcvh0000gn/T/pip-build-ru_AAg/pyswath/setup.py", line 7, in <module>
        import pyswath
      File "pyswath/__init__.py", line 18, in <module>
        from raster_tools import *
      File "pyswath/raster_tools.py", line 19, in <module>
        raise ModuleError(u"ERROR : Module " + module + " not present. \n\n Please, install it \
    NameError: name 'ModuleError' is not defined 
```

I don't see `ModuleError` defined or imported anywhere, or do I miss something?

(Benoit and Audrey from GFZ section 5.5)

**Comment by robertxa** [comment]
Thanks a lot Benoit for the feedback !

I have made an error in the way to raise the error when a module is missing. I correct it and pushed the new version in Github. It should now work fine !
